### ISSUE TITLE
[Bug]: Doesn't work with default config

### ISSUE THREAD

**Issue by ilovefreesw** [prostgles/ui#1]
### What happened?

It should open the main UI
but i see ECONNREFUSED: Could not connect to database.

![image](https://user-images.githubusercontent.com/77317006/149676111-c81bb75d-b231-409b-9512-31e3b1ab1b36.png)

### What OS are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
prgl_1      | Add a basic auth mode where user and sessions table are created
postgres_1  | performing post-bootstrap initialization ... ok
prgl_1      | testDBConnection fail {
prgl_1      |   connOpts: {
prgl_1      |     database: 'POSTGRES_DB',
prgl_1      |     user: 'POSTGRES_USER',
prgl_1      |     password: 'POSTGRES_PASSWORD',
prgl_1      |     host: 'postgres',
prgl_1      |     port: undefined,
prgl_1      |     ssl: false
prgl_1      |   },
prgl_1      |   err: Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |     errno: -111,
prgl_1      |     code: 'ECONNREFUSED',
prgl_1      |     syscall: 'connect',
prgl_1      |     address: '172.18.0.2',
prgl_1      |     port: 5432
prgl_1      |   }
prgl_1      | }
prgl_1      | getDBS Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |   errno: -111,
prgl_1      |   code: 'ECONNREFUSED',
prgl_1      |   syscall: 'connect',
prgl_1      |   address: '172.18.0.2',
prgl_1      |   port: 5432
prgl_1      | }
prgl_1      | WARNING: Creating a duplicate database object for the same connection.
prgl_1      |     at new Promise (<anonymous>)
prgl_1      |     at testDBConnection (/usr/src/app/server/dist/index.js:37:12)
prgl_1      |     at getDBS (/usr/src/app/server/dist/index.js:240:15)
prgl_1      | 
prgl_1      | testDBConnection fail {
prgl_1      |   connOpts: {
prgl_1      |     database: 'POSTGRES_DB',
prgl_1      |     user: 'POSTGRES_USER',
prgl_1      |     password: 'POSTGRES_PASSWORD',
prgl_1      |     host: 'postgres',
prgl_1      |     port: undefined,
prgl_1      |     ssl: false
prgl_1      |   },
prgl_1      |   err: Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |     errno: -111,
prgl_1      |     code: 'ECONNREFUSED',
prgl_1      |     syscall: 'connect',
prgl_1      |     address: '172.18.0.2',
prgl_1      |     port: 5432
prgl_1      |   }
prgl_1      | }
prgl_1      | getDBS Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |   errno: -111,
prgl_1      |   code: 'ECONNREFUSED',
prgl_1      |   syscall: 'connect',
prgl_1      |   address: '172.18.0.2',
prgl_1      |   port: 5432
prgl_1      | }
prgl_1      | WARNING: Creating a duplicate database object for the same connection.
prgl_1      |     at new Promise (<anonymous>)
prgl_1      |     at testDBConnection (/usr/src/app/server/dist/index.js:37:12)
prgl_1      |     at getDBS (/usr/src/app/server/dist/index.js:240:15)
prgl_1      | 
prgl_1      | testDBConnection fail {
prgl_1      |   connOpts: {
prgl_1      |     database: 'POSTGRES_DB',
prgl_1      |     user: 'POSTGRES_USER',
prgl_1      |     password: 'POSTGRES_PASSWORD',
prgl_1      |     host: 'postgres',
prgl_1      |     port: undefined,
prgl_1      |     ssl: false
prgl_1      |   },
prgl_1      |   err: Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |     errno: -111,
prgl_1      |     code: 'ECONNREFUSED',
prgl_1      |     syscall: 'connect',
prgl_1      |     address: '172.18.0.2',
prgl_1      |     port: 5432
prgl_1      |   }
prgl_1      | }
prgl_1      | getDBS Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |   errno: -111,
prgl_1      |   code: 'ECONNREFUSED',
prgl_1      |   syscall: 'connect',
prgl_1      |   address: '172.18.0.2',
prgl_1      |   port: 5432
prgl_1      | }
prgl_1      | WARNING: Creating a duplicate database object for the same connection.
prgl_1      |     at new Promise (<anonymous>)
prgl_1      |     at testDBConnection (/usr/src/app/server/dist/index.js:37:12)
prgl_1      |     at getDBS (/usr/src/app/server/dist/index.js:240:15)
prgl_1      | 
prgl_1      | testDBConnection fail {
prgl_1      |   connOpts: {
prgl_1      |     database: 'POSTGRES_DB',
prgl_1      |     user: 'POSTGRES_USER',
prgl_1      |     password: 'POSTGRES_PASSWORD',
prgl_1      |     host: 'postgres',
prgl_1      |     port: undefined,
prgl_1      |     ssl: false
prgl_1      |   },
prgl_1      |   err: Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |     errno: -111,
prgl_1      |     code: 'ECONNREFUSED',
prgl_1      |     syscall: 'connect',
prgl_1      |     address: '172.18.0.2',
prgl_1      |     port: 5432
prgl_1      |   }
prgl_1      | }
prgl_1      | getDBS Error: connect ECONNREFUSED 172.18.0.2:5432
prgl_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
prgl_1      |   errno: -111,
prgl_1      |   code: 'ECONNREFUSED',
prgl_1      |   syscall: 'connect',
prgl_1      |   address: '172.18.0.2',
prgl_1      |   port: 5432
prgl_1      | }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prostgles** [comment]
Normally you get these errors during DB initialisation and shortly after (5-35 seconds) it should restart itself and work normally.

Does it just get stuck there?
What version docker you are using?
```
docker -v
docker-compose -v
```

**Comment by prostgles** [comment]
Closing issue due to no response
